// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFmmsdY0NgA6V9Z__94nZHJZ-8NKbz1Uc',
    appId: '1:1010402276504:web:4b02e1d01fca6989210ced',
    messagingSenderId: '1010402276504',
    projectId: 'dude-1621c',
    authDomain: 'dude-1621c.firebaseapp.com',
    storageBucket: 'dude-1621c.firebasestorage.app',
    measurementId: 'G-PPWCT9KLH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXDd_iRfBvcJgWeuAZYn1i4JhEHRNVxEM',
    appId: '1:1010402276504:android:cd9235771a56c071210ced',
    messagingSenderId: '1010402276504',
    projectId: 'dude-1621c',
    storageBucket: 'dude-1621c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUBdpxJi2LfuvMdGUYg8_RK_NqRXq2L20',
    appId: '1:1010402276504:ios:466f90ec70f6e267210ced',
    messagingSenderId: '1010402276504',
    projectId: 'dude-1621c',
    storageBucket: 'dude-1621c.firebasestorage.app',
    iosBundleId: 'com.dude.dudeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUBdpxJi2LfuvMdGUYg8_RK_NqRXq2L20',
    appId: '1:1010402276504:ios:466f90ec70f6e267210ced',
    messagingSenderId: '1010402276504',
    projectId: 'dude-1621c',
    storageBucket: 'dude-1621c.firebasestorage.app',
    iosBundleId: 'com.dude.dudeapp',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFmmsdY0NgA6V9Z__94nZHJZ-8NKbz1Uc',
    appId: '1:1010402276504:web:8c4d4a6cb08b7acc210ced',
    messagingSenderId: '1010402276504',
    projectId: 'dude-1621c',
    authDomain: 'dude-1621c.firebaseapp.com',
    storageBucket: 'dude-1621c.firebasestorage.app',
    measurementId: 'G-M8DF23L3CR',
  );
}
